name: Intreccio2
favicon: null
layout_spectrum: 0.10944629507139325
typography_spectrum: 0.21528668073005974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6412829922046512
  lightness: 0.3579678626265377
  saturation: 0.1218887350987643
  rhythmicContrast: 0.7248328186105937
purpose: []
